### ISSUE TITLE
[references] reference codelens sometimes shows 'Error finding references'

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/go-language-server#13]
See https://github.com/theia-ide/theia-apps/issues/13

**Comment by JanKoehnlein** [comment]
Same in VSCode :-( guru reports
```
guru: query object not found during reloading
```
during reference finding for codelens

**Comment by JanKoehnlein** [comment]
https://github.com/Microsoft/vscode-go/issues/977

**Comment by JanKoehnlein** [comment]
References seem to work only when the Go workspace is arranged as described in https://golang.org/doc/code.html. It's a limitation of the underlying `guru` tool. Nothing we could fix here.

**Comment by thediveo** [comment]
This breaks down again with the advent of go modules: in a perfect valid go module layout, I see lots of 0 references, as well as "Error finding references" ... both of which are wrong.

**Comment by JanKoehnlein** [comment]
The microsoft/vscode-go extension has started to incorporate [gopls](https://github.com/golang/go/wiki/gopls), the Go language server provided by the Go team itself. You may consider switching as well.
