### ISSUE TITLE
Can't open some .go files

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/go-language-server#14]
Something like this was reported by our internal users, but it's the first time I witness it myself. See attached video. 

I was using the theiaide/theia-go image (https://hub.docker.com/r/theiaide/theia-go/), pulled fresh today. In it, I cloned the golang repo (https://github.com/golang/go.git) and noticed I could not open file src/bufio/bufio_test.go . However I am able to open other .go files in the same directory. The file itself looks fine; I can "cat" it successfully.

This may not consistently reproducable (it works for me using a different, internal docker image, that also has golang LS).

Here's the exception: 
```
Uncaught (in promise) A resource provider for 'file:///home/theia/go/src/bufio/bufio_test.go' is not registered.
rejected @ opener-service.ts:6
Promise.then (async)
step @ opener-service.ts:6
fulfilled @ opener-service.ts:6
Promise.then (async)
step @ opener-service.ts:6
(anonymous) @ opener-service.ts:6
__awaiter @ opener-service.ts:6
open @ opener-service.ts:71
FileNavigatorModel.doOpenNode @ navigator-model.ts:32
TreeModel.openNode @ tree-model.ts:238
TreeWidget.handleDblClickEvent @ tree-widget.ts:280
ondblclick @ tree-widget.ts:131
```
![peek 2018-02-01 08-01](https://user-images.githubusercontent.com/25749063/35681366-26460d38-072b-11e8-8e94-dd90d64f8970.gif)

**Comment by JanKoehnlein** [comment]
I cannot reproduce that. Was the file already open from last session? Did you try to reset the workspace?

**Comment by marcdumais-work** [comment]
Not sure, it's possible it was open from a previous session. Will keep an eye out if I see this happening again, and try resetting the workspace to see if it helps.

**Comment by JanKoehnlein** [comment]
Can I close this? It does not seem to happen anymore.

**Comment by marcdumais-work** [comment]
I have also not seen this issue since the report. Closing.
