### ISSUE TITLE
Try to find a solution for selection sensitive commands

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/go-language-server#3]
On the LS, we don't have selection. Would be great if the client sent the selection as an argument with the commands that need it. A wrapper command on the client could be helpful.

**Comment by svenefftinge** [comment]
We could add a selectionChanged notification to the protocol

**Comment by JanKoehnlein** [comment]
As far as I can see, these are mainly new commands, so for Theia we could solve that by adding the selection as a command argument in the calling Theia extension. Feels a bit less invasive and less verbose than forwarding each new selection to the LS.

**Comment by JanKoehnlein** [comment]
2b972eb3287e2368d2ec3ec4672f390ac4f9972f
